# Use the official Node.js 20 image as a base
FROM node:20-slim

# Create and set the working directory inside the container
WORKDIR /usr/src/app

# Install dependencies (assuming you also have a package.json)
COPY package.json ./
RUN npm install --omit=dev

# Copy the application source code
COPY . .

# Cloud Run services must listen on the port defined by the PORT environment variable
ENV PORT 8080
EXPOSE 8080

# Command to run the application
CMD [ "node", "index.js" ]
